ARG NODE_VERSION=24
ARG PORT

FROM node:$NODE_VERSION AS base

WORKDIR /app

FROM base AS builder

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn lerna bootstrap --scope=server
RUN yarn build --scope=server


FROM node:$NODE_VERSION AS production
WORKDIR /app

COPY --from=builder /app/packages/server/dist ./dist
COPY --from=builder /app/packages/server/package.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE $PORT

CMD ["yarn", "runInDocker"]