import type { EEnemy, TEnemy } from '../types';

export const ENEMIES: Record<EEnemy, TEnemy> = {
  scavScum: {
    name: 'Бандиты-Падальщики',
    accuracy: 1,
    defense: 1,
    power: 1,
    health: 20,
    minAttack: 1,
    maxAttack: 3,
    attackSpeed: 2000,
    exp: 10,
    iconSrc: 'img/enemies/scavScum.png',
    lvl: 1,
  },
  gibberingHorde: {
    name: 'Бомжи-Мутанты',
    accuracy: 1,
    defense: 1,
    power: 1,
    health: 40,
    minAttack: 2,
    maxAttack: 4,
    attackSpeed: 1500,
    exp: 20,
    lvl: 1,
    iconSrc: 'img/enemies/gibberingHorde.png',
  },
  scrapjackers: {
    name: 'Ловчие-Таксидермисты',
    accuracy: 1,
    defense: 1,
    power: 1,
    health: 30,
    minAttack: 3,
    maxAttack: 5,
    attackSpeed: 1500,
    exp: 30,
    iconSrc: 'img/enemies/scrapjackers.png',
    lvl: 1,
  },
  ratKing: {
    name: 'Крысиный Король',
    accuracy: 10,
    defense: 10,
    power: 10,
    health: 500,
    minAttack: 4,
    maxAttack: 12,
    attackSpeed: 1000,
    exp: 100,
    iconSrc: 'img/enemies/ratKing.png',
    lvl: 2,
    damageMultiplier: 1.1,
  },

  // Группа 2
  gutterPunk: {
    name: 'Уличные Боевики',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 2,
    iconSrc: 'img/enemies/gutterPunk.png',
  },
  shadyBackAlleyDealer: {
    name: 'Торговец-Обманщик',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 2,
    iconSrc: 'img/enemies/shadyBackAlleyDealer.png',
  },
  roadRashRider: {
    name: 'Гонщик-Наездник',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 2,
    iconSrc: 'img/enemies/roadRashRider.png',
  },
  gangLeaderSledgehammer: {
    name: 'Главарь Банды "Штурмовой Молот"',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 3,
    damageMultiplier: 1.1,
    iconSrc: 'img/enemies/gangLeaderSledgehammer.png',
  },

  // Группа 3
  rentaCop: {
    name: 'Корпоративная Охрана',
    accuracy: 30,
    defense: 30,
    power: 30,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 3,
    iconSrc: 'img/enemies/rentaCop.png',
  },
  adDroneAggressor: {
    name: 'Рекламный Дрон-Провокатор',
    accuracy: 30,
    defense: 30,
    power: 30,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 3,
    iconSrc: 'img/enemies/adDroneAggressor.png',
  },
  mallMaulers: {
    name: 'Банда "Шопоголиков"',
    accuracy: 30,
    defense: 30,
    power: 30,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 3,
    iconSrc: 'img/enemies/mallMaulers.png',
  },
  securityAiSphinx: {
    name: 'Охранный ИИ "Сфинкс"',
    accuracy: 30,
    defense: 30,
    power: 30,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 4,
    damageMultiplier: 1.2,
    iconSrc: 'img/enemies/securityAiSphinx.png',
  },

  // Группа 4
  undergroundBrawler: {
    name: 'Подпольный Боец',
    accuracy: 40,
    defense: 40,
    power: 40,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 4,
    iconSrc: 'img/enemies/undergroundBrawler.png',
  },
  ghostInTheSystem: {
    name: 'Хакер-Призрак',
    accuracy: 40,
    defense: 40,
    power: 40,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 4,
    iconSrc: 'img/enemies/ghostInTheSystem.png',
  },
  graftedBrute: {
    name: 'Модифицированный "Зверь"',
    accuracy: 40,
    defense: 40,
    power: 40,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 4,
    iconSrc: 'img/enemies/graftedBrute.png',
  },
  legendaryMechanic: {
    name: 'Легендарный Механик "Док"',
    accuracy: 40,
    defense: 40,
    power: 40,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 5,
    damageMultiplier: 1.2,
    iconSrc: 'img/enemies/legendaryMechanic.png',
  },

  // Группа 5
  corporateSecurityOfficer: {
    name: 'Корпоративный Офицер Безопасности',
    accuracy: 50,
    defense: 50,
    power: 50,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 5,
    iconSrc: 'img/enemies/corporateSecurityOfficer.png',
  },
  surveillanceDroneVulture: {
    name: 'Следящий Дрон "Стервятник"',
    accuracy: 50,
    defense: 50,
    power: 50,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 5,
    iconSrc: 'img/enemies/surveillanceDroneVulture.png',
  },
  combatCustodianAndroid: {
    name: 'Боевой Андроид-Уборщик',
    accuracy: 50,
    defense: 50,
    power: 50,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 5,
    iconSrc: 'img/enemies/combatCustodianAndroid.png',
  },
  assaultLeaderGreyHornet: {
    name: 'Тактический Штурмовой Лидер "Серая Шершень"',
    accuracy: 50,
    defense: 50,
    power: 50,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 6,
    damageMultiplier: 1.2,
    iconSrc: 'img/enemies/assaultLeaderGreyHornet.png',
  },

  // Группа 6
  specOpsTrooper: {
    name: 'Солдат Спецназа',
    accuracy: 60,
    defense: 60,
    power: 60,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 6,
    iconSrc: 'img/enemies/specOpsTrooper.png',
  },
  phantomSniper: {
    name: 'Снайпер-Призрак',
    accuracy: 60,
    defense: 60,
    power: 60,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 6,
    iconSrc: 'img/enemies/phantomSniper.png',
  },
  combatEngineer: {
    name: 'Сапёр-Инженер',
    accuracy: 60,
    defense: 60,
    power: 60,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 6,
    iconSrc: 'img/enemies/combatEngineer.png',
  },
  squadCommanderValkyrie: {
    name: 'Командир Отряда "Валькирия"',
    accuracy: 60,
    defense: 60,
    power: 60,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 7,
    damageMultiplier: 1.2,
    iconSrc: 'img/enemies/squadCommanderValkyrie.png',
  },

  // Группа 7
  corperateResearcherGoneMad: {
    name: 'Корпоративный Учёный-Оборотень',
    accuracy: 70,
    defense: 70,
    power: 70,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 7,
    iconSrc: 'img/enemies/corperateResearcherGoneMad.png',
  },
  unstableSecurityDronePrototype: {
    name: 'Нестабильный Прототип Охранного Дрона',
    accuracy: 70,
    defense: 70,
    power: 70,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 7,
    iconSrc: 'img/enemies/unstableSecurityDronePrototype.png',
  },
  bioEngineeredHorror: {
    name: 'Био-Инженерный Ужас',
    accuracy: 70,
    defense: 70,
    power: 70,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 7,
    iconSrc: 'img/enemies/bioEngineeredHorror.png',
  },
  leadScientistCuratorDrArkadyVolf: {
    name: 'Главный Учёный-Куратор Доктор Аркадий Вольф',
    accuracy: 70,
    defense: 70,
    power: 70,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 8,
    damageMultiplier: 1.3,
    iconSrc: 'img/enemies/leadScientistCuratorDrArkadyVolf.png',
  },

  // Группа 8
  elitePrivateGuards: {
    name: 'Элитные Частные Охранники',
    accuracy: 80,
    defense: 80,
    power: 80,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 8,
    iconSrc: 'img/enemies/elitePrivateGuards.png',
  },
  smartHomeSystem: {
    name: 'Система "Умный Дом"',
    accuracy: 80,
    defense: 80,
    power: 80,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 8,
    iconSrc: 'img/enemies/smartHomeSystem.png',
  },
  automatedCombatButler: {
    name: 'Автоматизированный Боевой Дворецкий',
    accuracy: 80,
    defense: 80,
    power: 80,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 8,
    iconSrc: 'img/enemies/automatedCombatButler.png',
  },
  legendaryArtisan: {
    name: 'Сам Легендарный Оружейник',
    accuracy: 80,
    defense: 80,
    power: 80,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 10,
    damageMultiplier: 1.3,
    iconSrc: 'img/enemies/legendaryArtisan.png',
  },

  // Группа 9
  eliteCyberGuard: {
    name: 'Элитная Кибер-Гвардия',
    accuracy: 90,
    defense: 90,
    power: 90,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 9,
    iconSrc: 'img/enemies/eliteCyberGuard.png',
  },
  realitySuppressor: {
    name: 'Подавитель Реальности',
    accuracy: 90,
    defense: 90,
    power: 90,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 9,
    iconSrc: 'img/enemies/realitySuppressor.png',
  },
  aiAspect: {
    name: 'Аспект ИИ',
    accuracy: 90,
    defense: 90,
    power: 90,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 9,
    iconSrc: 'img/enemies/aiAspect.png',
  },
  directorOfNewTechnologies: {
    name: 'Директор по Новым Технологиям',
    accuracy: 90,
    defense: 90,
    power: 90,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 10,
    damageMultiplier: 1.3,
    iconSrc: 'img/enemies/directorOfNewTechnologies.png',
  },

  // Группа 10
  shardsOfLostMinds: {
    name: 'Фрагменты Потерянных Сознаний',
    accuracy: 100,
    defense: 100,
    power: 100,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 10,
    iconSrc: 'img/enemies/shardsOfLostMinds.png',
  },
  thresholdGuardian: {
    name: 'Страж Порога',
    accuracy: 100,
    defense: 100,
    power: 100,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 10,
    iconSrc: 'img/enemies/thresholdGuardian.png',
  },
  echoOfTheFirstAI: {
    name: 'Отголосок Первого ИИ',
    accuracy: 100,
    defense: 100,
    power: 100,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 10,
    iconSrc: 'img/enemies/echoOfTheFirstAI.png',
  },
  abyss: {
    name: 'Бездна',
    accuracy: 100,
    defense: 100,
    power: 100,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 12,
    damageMultiplier: 1.4,
    iconSrc: 'img/enemies/abyss.png',
  },
};
