import type { TSkills } from '../types';

export const SKILLS: TSkills = {
  carTheft: {
    name: 'Кража автомобилей',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description: 'Угон транспортных средств для последующей продажи или разборки на запчасти.',
  },
  corporateRaids: {
    name: 'Атаки на корпорации',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description: 'Осада офисов крупных компаний с целью ограбления или уничтожения активов.',
  },
  employmentWork: {
    name: 'Работа по найму',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description: 'Выполнение заданий для корпораций или частных лиц.',
  },
  freelance: {
    name: 'Фрилансерские задания',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description:
      'Временные контракты на выполнение конкретных задач, таких как ремонт техники, обучение персонала или консультирование.',
  },
  hacking: {
    name: 'Взлом',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description:
      'Взлом компьютерных сетей и баз данных, получение секретных файлов или доступ к закрытым ресурсам.',
  },
  hostages: {
    name: 'Похищение людей',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description: 'Захват заложников для последующего выкупа или торговли органами.',
  },
  scavenging: {
    name: 'Сбор мусора',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description: 'Переработка отходов, добыча ценных металлов и компонентов из старых устройств.',
  },
  spy: {
    name: 'Шпионаж',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description: 'Сбор конфиденциальной информации, прослушивание разговоров или кража документов.',
  },
  mercenary: {
    name: 'Наемничество',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description:
      'Работа на криминальные организации, участие в вооруженных конфликтах или охранных операциях.',
  },
  productTesting: {
    name: 'Испытания продуктов',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description:
      'Участие в тестировании новых лекарств, оборудования или кибернетических протезов.',
  },
  research: {
    name: 'Исследования',
    lvl: 1,
    expToLvl: 1000,
    exp: 0,
    timeToGetExp: 2000,
    isActive: false,
    description:
      'Создание новых технологий, улучшение существующих устройств или модификация имплантатов.',
  },
};
