enum EItem {
  rustyIron = 'rustyIron',
  waterPipes = 'waterPipes',
}

const ENEMIES = {
  scavScum: {
    name: 'Бандиты-Падальщики',
    accuracy: 1,
    defense: 1,
    power: 1,
    health: 20,
    minAttack: 1,
    maxAttack: 3,
    attackSpeed: 2000,
    exp: 10,
    iconSrc: 'img/enemies/scavScum.png',
    lvl: 1,
  },
  gibberingHorde: {
    name: 'Бомжи-Мутанты',
    accuracy: 1,
    defense: 1,
    power: 1,
    health: 40,
    minAttack: 2,
    maxAttack: 4,
    attackSpeed: 1500,
    exp: 20,
    lvl: 1,
    iconSrc: 'img/enemies/gibberingHorde.png',
  },
  scrapjackers: {
    name: 'Ловчие-Таксидермисты',
    accuracy: 1,
    defense: 1,
    power: 1,
    health: 30,
    minAttack: 3,
    maxAttack: 5,
    attackSpeed: 1500,
    exp: 30,
    iconSrc: 'img/enemies/scrapjackers.png',
    lvl: 1,
  },
  ratKing: {
    name: 'Крысиный Король',
    accuracy: 10,
    defense: 10,
    power: 10,
    health: 500,
    minAttack: 4,
    maxAttack: 12,
    attackSpeed: 1000,
    exp: 100,
    iconSrc: 'img/enemies/ratKing.png',
    lvl: 2,
    damageMultiplier: 1.1,
  },

  gutterPunk: {
    name: 'Уличные Боевики',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 20,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 10,
    lvl: 2,
    iconSrc: 'img/enemies/gutterPunk.png',
  },
  shadyBackAlleyDealer: {
    name: 'Торговец-Обманщик',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 40,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 20,
    lvl: 2,
    iconSrc: 'img/enemies/shadyBackAlleyDealer.png',
  },
  roadRashRider: {
    name: 'Гонщик-Наездник',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 60,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 30,
    lvl: 2,
    iconSrc: 'img/enemies/roadRashRider.png',
  },
  gangLeaderSledgehammer: {
    name: 'Главарь Банды "Штурмовой Молот"',
    accuracy: 20,
    defense: 20,
    power: 20,
    health: 800,
    minAttack: 2,
    maxAttack: 12,
    attackSpeed: 2000,
    exp: 100,
    lvl: 3,
    damageMultiplier: 1.1,
    iconSrc: 'img/enemies/gangLeaderSledgehammer.png',
  },
};

export const LOCATIONS = {
  megaplexDumps: {
    key: 'megaplexDumps',
    name: 'Свалки Мегаполиса',
    enemies: [ENEMIES.scavScum, ENEMIES.gibberingHorde, ENEMIES.scrapjackers],
    enemyBoss: ENEMIES.ratKing,
    enemysCount: 10,
    resources: [EItem.rustyIron],
    reward: 'Мусорный криптор',
    achievementText: 'Покинуть свалку',
    isComplete: true,
    img: '/img/raids/megaplexDumps.webp',
  },
  gutterStreets: {
    key: 'gutterStreets',
    name: 'Улицы Отбросов',
    enemies: [ENEMIES.gutterPunk, ENEMIES.shadyBackAlleyDealer, ENEMIES.roadRashRider],
    enemyBoss: ENEMIES.gangLeaderSledgehammer,
    enemysCount: 10,
    isComplete: true,
    resources: [EItem.waterPipes],
    reward: 'Уличный криптор',
    img: '/img/raids/gutterStreets.png',
  },
};
